### ISSUE TITLE
Log isn't appending

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/int-newsapps-template#1]
`foo &> /my/log/location.log` isn't capturing output. It's supposed to get `stderr`. Weirdly, it gets one and only one message:

```
ALTER ROLE
```

Which is coming from `scripts/_database.sh`.

**Comment by SHewitt95** [comment]
So, you only want `stderr`? Meaning, I could send `stdout` to `dev/null`, and that'd be fine?

I ask because what you have now -- `&>` -- will save both `stdout` and `stderr` to the log. At the same time, however, `&>` will **overwrite** the log, which is why you only see `ALTER ROLE` as the output.

If you want both `stdout` and `stderr` saved in and appended to the log, `&>` should be replaced with `>> /my/log/location.log 2>>&1`.

If you just want `stderr`, then `> /dev/null 2>>/my/log/location.log` would replace `&>`.

[Source](https://stackoverflow.com/questions/876239/how-can-i-redirect-and-append-both-stdout-and-stderr-to-a-file-with-bash/9895336)

P.S: I'm noting this and not submitting a pull request because my comp is currently not letting me push my commits.

**Comment by SHewitt95** [comment]
(Testing on my new computer has manifested contrary results. Investigating.)

**Comment by rshorey** [comment]
I merged this pull request. hopefully that was the plan. it didn't majorly break anything on my machine. but I didn't really look into the new features at all. will reopen if this remains a problem for anyone.
